// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
static struct imu s_imu = {42.1234, 42, 42, 42, 42, 42};
void glue_get_imu(struct imu *data) {
  *data = s_imu;  // Sync with your device
}

static struct power_service_settings s_power_service_settings = {12, 12.5, 16};
void glue_get_power_service_settings(struct power_service_settings *data) {
  *data = s_power_service_settings;  // Sync with your device
}
void glue_set_power_service_settings(struct power_service_settings *data) {
  s_power_service_settings = *data; // Sync with your device
}

static struct state s_state = {true, 1.2, "Unknown", 12, 1, 10, 42};
void glue_get_state(struct state *data) {
  *data = s_state;  // Sync with your device
}
